# Google Cloud Build configuration for MusicStream Lite
# This file defines the CI/CD pipeline for deploying to Google Cloud Run

# Global substitutions (set in Cloud Build triggers)
substitutions:
  _SERVICE_NAME: 'musicstream-service'
  _REGION: 'us-central1'
  _ARTIFACT_REGISTRY: 'us-central1-docker.pkg.dev'
  _REPOSITORY: 'musicstream'

# Build steps
steps:
  # ==========================================================================
  # BUILD CATALOG SERVICE
  # ==========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-catalog-service'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🏗️ Building Catalog Service..."
        docker build \
          -t ${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/catalog-service:${SHORT_SHA} \
          -t ${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/catalog-service:latest \
          ./backend/catalog-service

  # ==========================================================================
  # BUILD USER SERVICE
  # ==========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-user-service'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "👤 Building User Service..."
        docker build \
          -t ${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/user-service:${SHORT_SHA} \
          -t ${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/user-service:latest \
          ./backend/user-service

  # ==========================================================================
  # BUILD ANALYTICS SERVICE
  # ==========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-analytics-service'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "📊 Building Analytics Service..."
        docker build \
          -t ${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/analytics-service:${SHORT_SHA} \
          -t ${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/analytics-service:latest \
          ./backend/analytics-service

  # ==========================================================================
  # BUILD FRONTEND
  # ==========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🎨 Building Frontend..."
        docker build \
          -t ${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/frontend:${SHORT_SHA} \
          -t ${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/frontend:latest \
          ./frontend/react-app

  # ==========================================================================
  # PUSH IMAGES TO ARTIFACT REGISTRY
  # ==========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-catalog-service'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "📤 Pushing Catalog Service to Artifact Registry..."
        docker push ${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/catalog-service:${SHORT_SHA}
        docker push ${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/catalog-service:latest

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-user-service'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "📤 Pushing User Service to Artifact Registry..."
        docker push ${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/user-service:${SHORT_SHA}
        docker push ${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/user-service:latest

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-analytics-service'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "📤 Pushing Analytics Service to Artifact Registry..."
        docker push ${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/analytics-service:${SHORT_SHA}
        docker push ${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/analytics-service:latest

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "📤 Pushing Frontend to Artifact Registry..."
        docker push ${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/frontend:${SHORT_SHA}
        docker push ${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/frontend:latest

  # ==========================================================================
  # DEPLOY TO CLOUD RUN
  # ==========================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-catalog-service'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo " 🚀 Deploying Catalog Service to Cloud Run..."
        gcloud run deploy catalog-service \
          --image=${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/catalog-service:${SHORT_SHA} \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --memory=512Mi \
          --cpu=1 \
          --max-instances=5 \
          --set-env-vars=DB_HOST=${_DB_HOST},DB_NAME=${_DB_NAME},DB_USER=${_DB_USER} \
          --set-secrets=DB_PASSWORD=projects/${PROJECT_ID}/secrets/db-password:latest

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-user-service'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🚀 Deploying User Service to Cloud Run..."
        gcloud run deploy user-service \
          --image=${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/user-service:${SHORT_SHA} \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --memory=512Mi \
          --cpu=1 \
          --max-instances=5 \
          --set-env-vars=DB_HOST=${_DB_HOST},DB_NAME=${_DB_NAME},DB_USER=${_DB_USER} \
          --set-secrets=DB_PASSWORD=projects/${PROJECT_ID}/secrets/db-password:latest,JWT_SECRET=projects/${PROJECT_ID}/secrets/jwt-secret:latest

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-analytics-service'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🚀 Deploying Analytics Service to Cloud Run..."
        gcloud run deploy analytics-service \
          --image=${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/analytics-service:${SHORT_SHA} \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --memory=512Mi \
          --cpu=1 \
          --max-instances=5 \
          --set-env-vars=PROJECT_ID=${PROJECT_ID}

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🚀 Deploying Frontend to Cloud Run..."
        gcloud run deploy frontend \
          --image=${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/frontend:${SHORT_SHA} \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --memory=512Mi \
          --cpu=1 \
          --max-instances=3 \
          --set-env-vars=REACT_APP_API_URL=https://catalog-service-${_HASH}.${_REGION}.run.app

  # ==========================================================================
  # RUN TESTS (Optional)
  # ==========================================================================
  - name: 'node:18'
    id: 'run-tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🧪 Running tests..."
        cd backend/catalog-service && npm test || echo "Catalog tests failed"
        cd ../user-service && npm test || echo "User tests failed"
        cd ../analytics-service && npm test || echo "Analytics tests failed"

  # ==========================================================================
  # SECURITY SCAN (Optional)
  # ==========================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'vulnerability-scan'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔒 Scanning for vulnerabilities..."
        gcloud artifacts docker images scan \
          ${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/catalog-service:${SHORT_SHA}
        gcloud artifacts docker images scan \
          ${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/user-service:${SHORT_SHA}
        gcloud artifacts docker images scan \
          ${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/analytics-service:${SHORT_SHA}

# Timeout and machine type
timeout: 1800s # 30 minutes
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Artifacts to store
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}_cloudbuild/artifacts/'
    paths: ['**/*']

# Tags for the build
tags:
  - 'musicstream'
  - 'production'
  - 'microservices'