# Google Cloud Build configuration for MusicStream Lite Frontend
# This file builds and deploys the React frontend to Google Cloud Run

# Global substitutions
substitutions:
  _FRONTEND_SERVICE_NAME: 'musicstream-frontend'
  _REGION: 'us-central1'
  _ARTIFACT_REGISTRY: 'us-central1-docker.pkg.dev'
  _REPOSITORY: 'musicstream'

# Build steps
steps:
  # ==========================================================================
  # INSTALL DEPENDENCIES AND RUN TESTS
  # ==========================================================================
  - name: 'node:18'
    id: 'install-dependencies'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "📦 Installing frontend dependencies..."
        cd frontend/react-app
        npm ci --only=production --audit=false
        echo "✅ Dependencies installed successfully"

  - name: 'node:18'
    id: 'run-tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🧪 Running frontend tests..."
        cd frontend/react-app
        npm test -- --watchAll=false --coverage --passWithNoTests
        echo "✅ Tests completed"

  - name: 'node:18'
    id: 'run-lint'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔍 Running ESLint..."
        cd frontend/react-app
        npx eslint src/ --ext .js,.jsx,.ts,.tsx --max-warnings=0
        echo "✅ Lint completed"

  # ==========================================================================
  # BUILD REACT APPLICATION
  # ==========================================================================
  - name: 'node:18'
    id: 'build-react'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🏗️ Building React application..."
        cd frontend/react-app
        
        # Create environment file for build
        cat > .env.production << EOL
        REACT_APP_API_URL=https://api.musicstream.${_DOMAIN}
        REACT_APP_USER_SERVICE_URL=https://api.musicstream.${_DOMAIN}
        REACT_APP_ANALYTICS_SERVICE_URL=https://api.musicstream.${_DOMAIN}
        REACT_APP_ENV=production
        REACT_APP_VERSION=${TAG_NAME:-$SHORT_SHA}
        REACT_APP_SENTRY_DSN=${_SENTRY_DSN}
        REACT_APP_GA_TRACKING_ID=${_GA_TRACKING_ID}
        EOL
        
        # Build the application
        npm run build
        echo "✅ React build completed"
        
        # Create build info file
        echo "Build: ${SHORT_SHA}" > build/build-info.txt
        echo "Tag: ${TAG_NAME:-latest}" >> build/build-info.txt
        echo "Date: $(date)" >> build/build-info.txt

  # ==========================================================================
  # SECURITY SCAN OF DEPENDENCIES
  # ==========================================================================
  - name: 'node:18'
    id: 'security-scan'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔒 Scanning for vulnerabilities..."
        cd frontend/react-app
        npm audit --audit-level=high || echo "⚠️  Vulnerabilities found, but continuing build"
        echo "✅ Security scan completed"

  # ==========================================================================
  # BUILD DOCKER IMAGE
  # ==========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-docker-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🐳 Building Docker image..."
        docker build \
          -t ${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/frontend:${SHORT_SHA} \
          -t ${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/frontend:latest \
          -f frontend/react-app/Dockerfile.prod \
          frontend/react-app
        echo "✅ Docker build completed"

  # ==========================================================================
  # RUN DOCKER SECURITY SCAN
  # ==========================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'scan-docker-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔍 Scanning Docker image for vulnerabilities..."
        gcloud artifacts docker images scan \
          ${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/frontend:${SHORT_SHA} \
          --format="json" || echo "⚠️  Scan completed with findings"
        echo "✅ Docker image scan completed"

  # ==========================================================================
  # PUSH TO ARTIFACT REGISTRY
  # ==========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-to-artifact-registry'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "📤 Pushing Docker image to Artifact Registry..."
        docker push ${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/frontend:${SHORT_SHA}
        docker push ${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/frontend:latest
        echo "✅ Images pushed successfully"

  # ==========================================================================
  # DEPLOY TO CLOUD RUN
  # ==========================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-to-cloud-run'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🚀 Deploying to Cloud Run..."
        
        # Deploy the frontend service
        gcloud run deploy ${_FRONTEND_SERVICE_NAME} \
          --image=${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/frontend:${SHORT_SHA} \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --memory=512Mi \
          --cpu=1 \
          --max-instances=5 \
          --min-instances=0 \
          --concurrency=80 \
          --timeout=300s \
          --set-env-vars=REACT_APP_API_URL=https://catalog-service-${_HASH}.${_REGION}.run.app \
          --labels=commit-sha=${SHORT_SHA},version=${TAG_NAME:-latest},service=frontend
        
        echo "✅ Deployment completed"
        
        # Get the service URL
        SERVICE_URL=$(gcloud run services describe ${_FRONTEND_SERVICE_NAME} \
          --region=${_REGION} \
          --format="value(status.url)")
        
        echo "🌐 Frontend deployed to: $SERVICE_URL"

  # ==========================================================================
  # RUN E2E TESTS (Optional)
  # ==========================================================================
  - name: 'node:18'
    id: 'e2e-tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🎯 Running E2E tests..."
        
        # Wait for deployment to be ready
        sleep 30
        
        # Get the service URL
        SERVICE_URL=$(gcloud run services describe ${_FRONTEND_SERVICE_NAME} \
          --region=${_REGION} \
          --format="value(status.url)")
        
        echo "Testing service at: $SERVICE_URL"
        
        # Run basic health check
        if curl -f "$SERVICE_URL" > /dev/null 2>&1; then
          echo "✅ E2E health check passed"
        else
          echo "❌ E2E health check failed"
          exit 1
        fi

  # ==========================================================================
  # UPDATE CLOUD DNS (If using custom domain)
  # ==========================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'update-dns'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🌍 Updating DNS records..."
        
        # Get the Cloud Run service IP
        SERVICE_IP=$(gcloud run services describe ${_FRONTEND_SERVICE_NAME} \
          --region=${_REGION} \
          --format="value(status.address.url)" | sed 's|https://||')
        
        # Update DNS record (example for Cloud DNS)
        if [ ! -z "${_DOMAIN}" ]; then
          gcloud dns record-sets transaction start --zone=${_DNS_ZONE}
          gcloud dns record-sets transaction remove --zone=${_DNS_ZONE} \
            --name="musicstream.${_DOMAIN}." --type=A --ttl=300
          gcloud dns record-sets transaction add --zone=${_DNS_ZONE} \
            --name="musicstream.${_DOMAIN}." --type=A --ttl=300 "$SERVICE_IP"
          gcloud dns record-sets transaction execute --zone=${_DNS_ZONE}
          echo "✅ DNS updated for musicstream.${_DOMAIN}"
        fi

  # ==========================================================================
  # SEND NOTIFICATIONS
  # ==========================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'send-notification'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "📢 Sending deployment notification..."
        
        SERVICE_URL=$(gcloud run services describe ${_FRONTEND_SERVICE_NAME} \
          --region=${_REGION} \
          --format="value(status.url)")
        
        # Send to Slack (example)
        if [ ! -z "${_SLACK_WEBHOOK}" ]; then
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"🎵 Frontend deployed successfully!\n• Version: ${SHORT_SHA}\n• Environment: production\n• URL: $SERVICE_URL\"}" \
            ${_SLACK_WEBHOOK}
        fi
        
        echo "✅ Notification sent"

# Timeout and machine type
timeout: 1200s # 20 minutes
options:
  machineType: 'E2_HIGHCPU_4'
  logging: CLOUD_LOGGING_ONLY
  diskSizeGb: 50

# Artifacts to store
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}_cloudbuild/frontend/'
    paths: 
      - 'frontend/react-app/build/**/*'
      - 'frontend/react-app/coverage/**/*'

# Tags for the build
tags:
  - 'frontend'
  - 'react'
  - 'musicstream'
  - 'production'

# Secret environment variables
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/slack-webhook
      env: '_SLACK_WEBHOOK'
    - versionName: projects/$PROJECT_ID/secrets/sentry-dsn
      env: '_SENTRY_DSN'
    - versionName: projects/$PROJECT_ID/secrets/ga-tracking-id
      env: '_GA_TRACKING_ID'